plugins {
    id 'com.android.application'
}

android {
    namespace 'com.beigel.screenTracker'
    compileSdk 35

    defaultConfig {
        applicationId "com.beigel.screenTracker"
        minSdk 27
        targetSdk 35
        versionCode 4
        versionName "1.2.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        // Vector-Drawables aktivieren
        vectorDrawables.useSupportLibrary = true
    }

    buildTypes {
        debug {
            applicationIdSuffix ".debug"
            debuggable true
        }

        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    buildFeatures {
        viewBinding true  // View Binding aktivieren
    }
}

dependencies {
    // Core-Bibliotheken
    implementation 'androidx.core:core:1.16.0'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'

    // UI-Komponenten
    implementation 'com.google.android.material:material:1.12.0'
    implementation "com.github.skydoves:colorpickerview:2.3.0"

    // Test-Bibliotheken
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.3.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.7.0'
}