plugins {
    id 'com.android.application'
}

android {
    namespace 'com.beigel.screenTracker'
    compileSdk 34

    defaultConfig {
        applicationId "com.beigel.screenTracker"
        minSdk 26
        targetSdk 34
        versionCode 3
        versionName "1.1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        // Vector-Drawables aktivieren
        vectorDrawables.useSupportLibrary = true
    }

    buildTypes {
        debug {
            applicationIdSuffix ".debug"
            debuggable true
        }

        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    buildFeatures {
        viewBinding true  // View Binding aktivieren
    }
}

dependencies {
    // Core-Bibliotheken
    implementation 'androidx.core:core:1.10.1'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'

    // UI-Komponenten
    implementation 'com.google.android.material:material:1.9.0'
    implementation "com.github.skydoves:colorpickerview:2.3.0"

    // Test-Bibliotheken
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}